### ISSUE TITLE
Create new repository via init

### ISSUE THREAD

**Issue by GuillaumeMilan** [danhper/elixir-git-cli#7]
Currently when you execute a `Git.init` command you can't give a repository as parameter. 

So to initialise the repository from the path we need to as: 

```
repo = Git.new "/path/to/repo"
Git.execute_command repo, "init", [], (fn _ -> {:ok, repo} end)
```

It would be great to be able to do this through the function `Git.init`

Thanks

**Comment by danhper** [comment]
Hi, sorry for the delay. I am happy to support this feature but I do not have time to implement it. If you want to send a PR I will be more than happy to merge it.
Thanks!
